VIA_ENABLE = yes
VIAL_ENABLE = yes

AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes

EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
QMK_SETTINGS = yes

VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = no
