AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
OLED_ENABLE = no
QMK_SETTINGS = yes
RGBLIGHT_ENABLE = no
VIA_ENABLE = yes
VIAL_ENABLE = yes
# Bootloader selection
BOOTLOADER = rp2040
CONVERT_TO=rp2040_ce