name: Build Vial firmware

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli@sha256:16c4916e95b99bf88d27b15aec8db409ee17265d1710287fde248c6666508966

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v5
        with:
          path: custom

      - name: Checkout Vial-QMK
        uses: actions/checkout@v5
        with:
          repository: vial-kb/vial-qmk
          ref: vial
          submodules: recursive
          path: vial-qmk

      - name: Mark directories as safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE/custom"
          git config --global --add safe.directory "$GITHUB_WORKSPACE/vial-qmk"

      - name: Install Vial-QMK Python requirements
        working-directory: vial-qmk
        run: python3 -m pip install -U -r requirements.txt

      - name: Copy Sofle Blue files
        run: |
          mkdir -p vial-qmk/keyboards/sofle
          cp -r custom/keyboards/sofle/blue vial-qmk/keyboards/sofle/

      - name: Build firmware
        working-directory: vial-qmk
        run: qmk compile -kb sofle/blue -km vial -e CONVERT_TO=promicro_rp2040

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: sofle-blue-vial-firmware
          path: |
            vial-qmk/.build/*.uf2
            vial-qmk/.build/*.hex
            vial-qmk/.build/*.bin
